### ISSUE TITLE
Comments count overlaps byline photo

### ISSUE THREAD

**Issue by Smylers** [guardian/frontend#6722]
The ‘n comments’ label overlaps the byline photos for Cif articles on index pages when under the 980 px breakpoint.

Here's the Cif index on a page that's 979 px wide showing the comment count right through the eyes of the contributors:
![cif_979_px](https://cloud.githubusercontent.com/assets/598534/4765653/efe4f2ce-5b41-11e4-8b1b-44f1ecebec06.png)

The same page at 980 px is fine:
![cif_980_px](https://cloud.githubusercontent.com/assets/598534/4765659/0f8d3fd2-5b42-11e4-9a00-1413918a9ac3.png)

**Comment by uplne** [comment]
Is there any reasonable fix for this?

**Comment by Smylers** [comment]
> Is there any reasonable fix for this?

Put a background colour on the ‘𝑛 comments’ label?

Using the same background colour as the box for that item (or a translucent version of it) would ensure the text is always readable, and would look identical to now in cases where the label doesn't overlap a picture.

This works for me on opinion boxes (with a pale grey background):

```CSS
.fc-item__meta a
{
  background-color: inherit;
  padding-right: 0.2em;
}
```

It looks like that was already somebody's intention for it to look like this, because there's already a handy 50% transparent background colour defined on the parent `<aside>`; the CSS already includes:

```CSS
.tone-comment--item .fc-item__meta
{
  background-color: rgba(239, 239, 236, 0.5);
}
```

Adding something equivalent for features boxes (maroon) made the comments labels visible over images there too:

```CSS
.tone-feature--item .fc-item__meta
{
  background-color: rgba(149, 28, 85, 0.5)
}
```

To avoid having to hunt for a place where the issue currently crops up on the site, I used the following temporary CSS to make the byline images wider:

```CSS
.ft-item__avatar__media .responsive-img
{
  width: 256px;
}
```

Then I looked at the [Lifestyle home page](http://www.theguardian.com/lifeandstyle) in Firefox with the window 882 px wide. The `width` setting makes the journalists look like they've put on a bit of weight over Christmas, but it ensures their photos overlap with the comments counter.
